//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cyient.MDT.WebAPI.Utilities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class mdtResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal mdtResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cyient.MDT.WebAPI.Utilities.mdtResource", typeof(mdtResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed successfully..
        /// </summary>
        internal static string ChangePasswordMessage {
            get {
                return ResourceManager.GetString("ChangePasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record has been deleted successfully..
        /// </summary>
        internal static string DeletedMessage {
            get {
                return ResourceManager.GetString("DeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User,
        ///Your password has been reset successfully. please login with new password given below..
        /// </summary>
        internal static string EmailBody {
            get {
                return ResourceManager.GetString("EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to some technical issue unable to send an email. please contact to administrator..
        /// </summary>
        internal static string EmailFailure {
            get {
                return ResourceManager.GetString("EmailFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been reset but due to some technical issue unable to send an email. please contact to administrator..
        /// </summary>
        internal static string ForgotPasswordEmailFailure {
            get {
                return ResourceManager.GetString("ForgotPasswordEmailFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been reset and sent to your registered email..
        /// </summary>
        internal static string ForgotPasswordEmailSuccess {
            get {
                return ResourceManager.GetString("ForgotPasswordEmailSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user name/password. please enter correct user name and password..
        /// </summary>
        internal static string InvalidCredential {
            get {
                return ResourceManager.GetString("InvalidCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password. please enter correct password..
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been lock. please click on forgot password to unlock your account..
        /// </summary>
        internal static string LockedAccount {
            get {
                return ResourceManager.GetString("LockedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login successfully..
        /// </summary>
        internal static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered 3 times wrong password. your account has been lock.
        ///please click on forgot password to unlock your account..
        /// </summary>
        internal static string MultipleWrongAttempts {
            get {
                return ResourceManager.GetString("MultipleWrongAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records not found for requested action..
        /// </summary>
        internal static string NoRecordMessage {
            get {
                return ResourceManager.GetString("NoRecordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record has been fetched successfully..
        /// </summary>
        internal static string RecordFoundMessage {
            get {
                return ResourceManager.GetString("RecordFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save the record due to some technical issue, please contact to administrator..
        /// </summary>
        internal static string RecordSavedFailure {
            get {
                return ResourceManager.GetString("RecordSavedFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record has been saved successfully..
        /// </summary>
        internal static string RecordSaveSuccess {
            get {
                return ResourceManager.GetString("RecordSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action completed successfully..
        /// </summary>
        internal static string SuccessMessage {
            get {
                return ResourceManager.GetString("SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an issue in system, please contact to administrator..
        /// </summary>
        internal static string TechnicalErrorMessage {
            get {
                return ResourceManager.GetString("TechnicalErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record has been updated successfully..
        /// </summary>
        internal static string UpdatedMessage {
            get {
                return ResourceManager.GetString("UpdatedMessage", resourceCulture);
            }
        }
    }
}
